// <auto-generated />
namespace GroupAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Robbiemigrationone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Robbiemigrationone));
        
        string IMigrationMetadata.Id
        {
            get { return "202107271844303_Robbiemigration one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
